name: tfmol37
channels:
  - defaults
  - rdkit
  - openbabel
dependencies:
  - absl-py
  - astor
  - cloudpickle
  - cython
  - joblib>=0.12.5
  - gast==0.2.2
  - google-pasta>=0.1.6
  - grpcio
  - h5py
  - markdown>=2.6.8
  - matplotlib
  - mock
  - msgpack-python<1.0.0
  - msgpack-numpy=0.4.3
  - networkx>=2.1
  - numpy=1.17
  - openbabel==2.4.1
  - palettable
  - pandas=0.23
  - pip
  - pillow
  - psutil
  - python=3.7
  - rdkit==2018.09.3.0
  - scikit-learn=0.19
  - scipy
  - seaborn=0.9
  - setuptools
  - tabulate>=0.7.7
  - termcolor>=1.1.0
  - tqdm
  - pyarrow>=0.9.0
  - pyzmq
  - werkzeug>=0.11.10
  - wrapt>=1.11.1
  - jsonschema
  - click
  - colorama
  - filelock
  - funcsigs
  - more-itertools>=4.0.0
  - packaging
  - py>=1.5.0
  - pyrsistent>=0.14.0
  - pytest
  - pyyaml
  - typing
  - requests
  - pip:
    #- guacamol==0.3.2
    - lmdb==0.94
    - pot==0.5.1
    - python-prctl
    - tensorflow-gpu==1.14
    - tensorflow-probability==0.7.0
    - tensorpack==0.8.9
    - ray==0.7.7
    - setproctitle
